version: ci{build}
image:
  - Visual Studio 2022

clone_depth: 5

build_script:
  - ps: dotnet publish --self-contained -f net8.0-windows -r win-x64 -c Release "FrankenDrift.Runner/FrankenDrift.Runner.Win" -p:VersionSuffix="$env:APPVEYOR_BUILD_VERSION" -p:PublishTrimmed=true -p:TrimMode=partial -p:BuiltInComInteropSupport=true -p:EnableUnsafeBinaryFormatterSerialization=false -p:EnableUnsafeUTF7Encoding=false -p:HttpActivityPropagationSupport=false -p:MetadataUpdaterSupport=false
  - ps: dotnet publish --self-contained -f net8.0 -r win-x64 -c Release  "FrankenDrift.GlkRunner/Frankendrift.GlkRunner.Gargoyle" -p:VersionSuffix="$env:APPVEYOR_BUILD_VERSION"
  - ps: dotnet publish --no-self-contained -f net8.0 -c Release "FrankenDrift.Runner/FrankenDrift.Runner.Gtk"

artifacts:
  - path: FrankenDrift.Runner/FrankenDrift.Runner.Win/bin/Release/net8.0-windows/win-x64/publish
  - path: FrankenDrift.Runner/FrankenDrift.Runner.Gtk/bin/Release/net8.0/publish
  - path: FrankenDrift.GlkRunner/FrankenDrift.GlkRunner.Gargoyle/bin/Release/net8.0/win-x64/publish
