version: ci{build}
image:
  - Visual Studio 2022

clone_depth: 5

install:
  - cd FrankenDrift.Runner/FrankenDrift.Runner.Win

build_script:
  - ps: dotnet publish --self-contained -f net6.0-windows -r win10-x64 -p:PublishReadyToRun=true -c Release -p:VersionSuffix="$env:APPVEYOR_BUILD_VERSION-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 8))"

artifacts:
  - path: FrankenDrift.Runner/FrankenDrift.Runner.Win/bin/Release/net6.0-windows/win10-x64/publish
